apiVersion: v1
kind: ConfigMap

metadata:
  name: fraud-config
  namespace: fraud

data:

  APP_NAME: Fraud Detection API

  MODEL_PATH: model/model.pkl

  LOG_LEVEL: INFO

  PORT: "8000"

  ENVIRONMENT: production