name: Deploy Fraud Detection

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: my-cluster
  HELM_RELEASE: fraud-api
  NAMESPACE: fraud
  ECR_REPOSITORY: frauddetectioncc

jobs:

  deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      # =====================================
      # Checkout
      # =====================================

      - name: Checkout Repository
        uses: actions/checkout@v4


      # =====================================
      # AWS Credentials
      # =====================================

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      # =====================================
      # ECR Login
      # =====================================

      - name: Login to Amazon ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v2


      # =====================================
      # Install kubectl
      # =====================================

      - name: Install kubectl
        uses: azure/setup-kubectl@v4


      # =====================================
      # Install Helm
      # =====================================

      - name: Install Helm
        uses: azure/setup-helm@v4


      # =====================================
      # Configure kubeconfig
      # =====================================

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME


      # =====================================
      # Verify Cluster
      # =====================================

      - name: Verify Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes


      # =====================================
      # Namespace
      # =====================================

      - name: Create Namespace
        run: |
          kubectl create namespace $NAMESPACE \
            --dry-run=client \
            -o yaml | kubectl apply -f -


      # =====================================
      # Deploy
      # =====================================

      - name: Deploy using Helm
        run: |

          helm upgrade --install $HELM_RELEASE \
            ./heml/fraud-chart \
            --namespace $NAMESPACE \
            --set image.repository=821656895219.dkr.ecr.us-east-1.amazonaws.com/frauddetectioncc \
            --set image.tag=latest


      # =====================================
      # Rollout
      # =====================================

      - name: Verify Deployment
        run: |
          kubectl rollout status \
            deployment/fraud-api-fraud-chart \
            -n $NAMESPACE \
            --timeout=300s


      # =====================================
      # Verify Resources
      # =====================================

      - name: Verify Resources
        run: |
          kubectl get pods -n $NAMESPACE
          kubectl get svc -n $NAMESPACE
